### ISSUE TITLE
Python 2-3 compatibility 

### ISSUE THREAD

**Issue by bartromgens** [aquatix/ns-api#11]
I am using ns-api in a small hobby project (https://github.com/bartromgens/ns-maps) that uses Python 3. I needed to make some small changes to get it working for Python 3, see https://github.com/bartromgens/ns-api3/tree/python3-compatibility. I tried to keep it backwards compatible with Python 2. However, I am new to the 2->3 conversion, and am not sure everything still works with Python 2 (because I did not test). 

I used this doc as a guideline: http://python-future.org/compatible_idioms.html. 
Will do some more tests later and send a pull request if everything looks ok.

**Comment by aquatix** [comment]
I quickly did a test with your branch and as long as I've got the `future` package installed, it seems to work. I'll do some more testing to be sure, but I think you can send the pull request.

**Comment by bartromgens** [comment]
Good. I will do a last check and send a pull request tonight.

**Comment by aquatix** [comment]
I tested the current version of [ns-notifications](https://github.com/aquatix/ns-notifications) against it and it seems to work fine with Python 2.7.10

**Comment by aquatix** [comment]
Python 3 compatible as of commit 4410ff4a17d8faa706191b52c59c6d73e8de1c6b

Please let me know if there are any issues, closing this ticket now.
