### ISSUE TITLE
TypeError if no trips were found

### ISSUE THREAD

**Issue by bartromgens** [aquatix/ns-api#12]
The following code,

```Python
import ns_api

nsapi = ns_api.NSAPI(USERNAME, APIKEY)
trips = nsapi.get_trips('12-01-2016 08:00', 'Utrecht Centraal', '', 'Amsterdam Van der Madeweg')
```

Results in the following exception,
```
Traceback (most recent call last):
  ...
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 857, in get_trips
    return self.parse_trips(raw_trips, requested_time)
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 811, in parse_trips
    for trip in obj['ReisMogelijkheden']['ReisMogelijkheid']:
TypeError: 'NoneType' object is not subscriptable
```

It is correct that there are no 'ReisMogelijkheden' from 'Amsterdam Van der Madeweg', but this is not correctly handled. I would expect to get an empty list of trips. 

Minor issue, which is easy to work around and/or fix. Just for the record.

**Comment by aquatix** [comment]
Good one. Currently it catches the error from the NS XML API and prints "Error in trips: Geen geldige 'fromStation' opgegeven", returning None (as the input is 'faulty'), but I guess an empty list would work just as well. Going to change that now and push a new version.

Thanks!

**Comment by bartromgens** [comment]
The input is valid in this case, meaning that the fromStation is in the list of stations given by nsapi. 

Your fix does not resolve the problem. `'error' in obj` is False so it moves on to for `trip in obj['ReisMogelijkheden']['ReisMogelijkheid']` and then raises a TypeError exception. That is at least what happens for me. 

I am fine with None or empty list as return from get_trips. Just not a TypeError exception.

**Comment by aquatix** [comment]
Oh my bad, I copied your example and there's "Utrecht Central" in there (mind the single 'a'), so I got a different error. Apparantly I need more coffee, as your issue is with something else entirely. Just reproduced, going to fix now.

**Comment by bartromgens** [comment]
Ah, my bad as well. Typo in the example that reproduces the error :) Sorry. Thanks for looking into it.

**Comment by aquatix** [comment]
No worries :) Shall I return None in both cases, or an empty list? I prefer None, as that shows that something went wrong.

**Comment by bartromgens** [comment]
Yes, I also prefer None.

**Comment by bartromgens** [comment]
Great. Thanks!
