### ISSUE TITLE
TypeError for specific input due to missing time for TripStop

### ISSUE THREAD

**Issue by bartromgens** [aquatix/ns-api#14]
The following code,
```python
import ns_api

nsapi = ns_api.NSAPI(USERNAME, APIKEY)
timestamp = "04-02-2016 08:00"
start = "Rotterdam Blaak"
via = ""
destination = "Amsterdam Centraal"

trips = nsapi.get_trips(timestamp, start, via, destination)
```

results in this TypeError exception,
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    trips = nsapi.get_trips(timestamp, start, via, destination)
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 858, in get_trips
    return self.parse_trips(raw_trips, requested_time)
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 813, in parse_trips
    newtrip = Trip(trip, requested_time)
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 550, in __init__
    trip_part = TripSubpart(part)
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 443, in __init__
    stop = TripStop(raw_stop)
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 384, in __init__
    self.time = load_datetime(part_dict['Tijd'], NS_DATETIME)
  File "/home/bart/dev/ns-maps/env/src/ns-api/ns_api.py", line 45, in load_datetime
    offset = value[-5:]
TypeError: 'NoneType' object is not subscriptable
```

This happens for a small number of start and destination combinations (I try about 30000 combinations :) ).
Cause is that `part_dict['Tijd']` is None when used [in this line](https://github.com/aquatix/ns-api/blob/master/ns_api.py#L383). Probably some missing information from NS. The rest of the trip data looks good.

Changing that line to,
````python
if part_dict is None or part_dict['Tijd'] is None:
    return
```
fixes it for me. But than you lose the full TripStop, which you may not want.

**Comment by aquatix** [comment]
Interesting catch :) I'll have the self.time of that TripStop default to, er, the first of January 2000. Or maybe setting it to None will be enough, but I'll have to test that.

**Comment by aquatix** [comment]
TripStop.time defaults to None now in this case (2f26293cd47bca1137f2761f8690175ddc8be36c) and doesn't seem to be causing issues here. Could you please test?

**Comment by bartromgens** [comment]
There is a missing datetime import at https://github.com/aquatix/ns-api/blob/master/ns_api.py#L803

If I import datetime, and run the test code again, I get an error at https://github.com/aquatix/ns-api/blob/master/ns_api.py#L337 where `self.time` is now `None`, but is required to be a datetime object for `datetimeutil.simple_time()`.

**Comment by aquatix** [comment]
Did you update to the nsapi version in requirements.txt? I moved some common functions to a new package called utilkit.

**Comment by aquatix** [comment]
I just read your remark again and are going to look into it ;)
