### ISSUE TITLE
Confusing departure_time_actual behavior

### ISSUE THREAD

**Issue by YarmoM** [aquatix/ns-api#19]
Hey!

Thanks again for updating the library in response to the API changes. I have made a PR to implement it in home assistant (home-assistant/home-assistant#30599) and with the reviewer, we stumbled upon a curious behavior and I wanted to ask @aquatix if you saw any benefit in changing it.

`departure_time_planned` does exactly what it says. It was the originally planned time.

`departure_time_actual` is a time if there is a delay, otherwise it is None. The name however suggests that it should either be the planned time or the delayed time but never None, since it's the "actual" time. The delayed state could then be determined by compared the planned time and the actual time.

Would love to hear your opinion on this!

**Comment by aquatix** [comment]
Frankly, I don't know why it was changed that way. I agree with your remarks, and will look into changing its behaviour back to its original state. I can't promise an ETA, but if life doesn't interfere, I might have a new release by the evening.

**Comment by YarmoM** [comment]
I wasn't aware that this was the old behavior. Now that I think of it, that makes sense because the HA integration kept crashing over it, meaning it must worked that way prior to 3.0.0.

If life does happen to interfere, I can have a look, just let me know. Thanks for your time!

**Comment by aquatix** [comment]
I did some updating and cleanups, and [released 3.0.1](https://pypi.org/project/nsapi/). I think 411ab7f0594a957b6f03d73ea720a25a780bad86 should fix the None issue. It falls back to the planned departure or arrival time in that case.

I do not have a test setup with the new API yet, so I can't test thoroughly yet. Let me know if this helped!
