### ISSUE TITLE
Possible improvements for 3.0.2

### ISSUE THREAD

**Issue by YarmoM** [aquatix/ns-api#20]
Thanks for the recent 3.0.1 changes. I was wondering if we could look at a few possible improvements and perhaps release a new minor update before updating home-assistant as we are discussing in home-assistant/home-assistant#26622.

1- The actual/planned behavior that happens for the time I think should also happen for the platform.
2- The API portal states the URL is "https://gateway.apiportal.ns.nl/reisinformatie-api/api" while this library uses "https://gateway.apiportal.ns.nl/public-reisinformatie/api". Obviously, both URLs seem to work but perhaps the library should use the one stated in the documentation.

I'm currently reading the code, but could you elaborate a little bit on the current behavior of delay and has_delay? Are they part of the NSAPI response?

**Comment by aquatix** [comment]
Thanks for the recent PR's, much appreciated. I also updated the documentation a bit, and did some cleanups.

has_delay is a convenience boolean, maybe not so necessary. delay is the actual delay in minutes (which you can obviously also check). They are both calculated by the library, based on the planned times and actual times.

**Comment by YarmoM** [comment]
Alrighty, thanks, I'll look into implementing these two in a future PR for home-assistant.

**Comment by YarmoM** [comment]
Thanks for the further updates you have made, looking good. Do you see it fit yet to release a new version?

Digging in NS documentation, NS-API 3.0.1 will stop working in a little over a week.

**Comment by aquatix** [comment]
Sure, can do that right now. Was kinda waiting for any further feedback you had, which we could incorporate. Lets release 3.0.2 for now, and hope HA can be updated soon too (seeing the feedback over there).

**Comment by aquatix** [comment]
Done: https://pypi.org/project/nsapi/3.0.2/

**Comment by YarmoM** [comment]
Thanks my man! Yes, the pressure is rising over there and I'm curious to see what happens when all setups crash on the same day.

Not much feedback for now, solid piece of code! Once the big NS change has passed, we could have another look for improvements
