### ISSUE TITLE
Get_trips result in keyerror

### ISSUE THREAD

**Issue by Wummeke** [aquatix/ns-api#32]
Hi, See also https://github.com/home-assistant/core/issues/78587

I can reproduce the error I get in home-Assistant in a separate Python script:

```
import ns_api
from datetime import datetime

now = datetime.now()
current_time = now.strftime("%d-%m-%Y %H:%M")


print("Current Time =", current_time)
ns = ns_api.NSAPI('7612f1390fc748dd9a521194d3d84e99')
_trips = ns.get_trips(current_time, 'Gvc', None, 'Ypb',  True, 0, 0)

result = list(_trips)
print (result)
```

Output:
```
Current Time = 01-10-2022 15:20
Traceback (most recent call last):
  File "/config/python_scripts/./ns_test.py", line 11, in <module>
    _trips = ns.get_trips(current_time, 'Gvc', None, 'Ypb',  True, 0, 0)
  File "/usr/local/lib/python3.10/site-packages/ns_api.py", line 928, in get_trips
    return self.parse_trips(raw_trips, requested_time)
  File "/usr/local/lib/python3.10/site-packages/ns_api.py", line 839, in parse_trips
    newtrip = Trip(trip, requested_time)
  File "/usr/local/lib/python3.10/site-packages/ns_api.py", line 608, in __init__
    trip_part = TripSubpart(part)
  File "/usr/local/lib/python3.10/site-packages/ns_api.py", line 442, in __init__
    self.transporter = part_dict['product']['operatorName']
KeyError: 'operatorName'
```

**Comment by aquatix** [comment]
Ah, that's not right indeed. Will take a look at it soon.

**Comment by hugoideler** [comment]
I can confirm that the tag `v3.1.0` has indeed fixed this bug. However, this tag is not yet published on PyPI: [the latest version there](https://pypi.org/project/nsapi/#history) is still `3.0.5`. This makes it more difficult to use this fix downstream.

Could you also update the PyPI package?

**Comment by aquatix** [comment]
Oh good point. I'll look into publishing a new version tomorrow, thanks for the reminder!

**Comment by aquatix** [comment]
Published https://github.com/aquatix/ns-api/releases/tag/v3.1.1 on pypi. It took a bit, as some modernisations were needed, but here we are :)

Let me know if everything works!

**Comment by hugoideler** [comment]
It works well, thanks for your quick response!
